### ISSUE TITLE
[Build] build on Ubuntu16.04 and fail when building third-party 

### ISSUE THREAD

**Issue by jimmyoic** [facebookresearch/TensorComprehensions#89]
- OS: Ubuntu 16.04
- How you installed TC (docker, conda, source): source
- Python version: 3.5.2
- CUDA/cuDNN version: 8.0
- GCC/GXX version (if compiling from source): 5.4.0
- LLVM/Tapir git hash used (if compiling from source): clang version 5.0.0 (get from the command below)

  To get the hash, run: `$HOME/clang+llvm-tapir5.0/bin/clang --version`

- Commit hash of our repo and submodules (if compiling from source): ea0c39dcede6850bd3e9553eee0d4f083681c314

In addition, including the following information will also be very helpful for us to diagnose the problem:

I followed "Building from Source in Non-Conda Environment"
 of [https://facebookresearch.github.io/TensorComprehensions/installation_non_conda.html](url) and problems happened when installing TC with caffe2 intergration. While the build.sh is trying to build some third-party such as Halide I got some error:

/home/jimmyoic/TensorComprehensions/third-party/halide/src/Error.cpp: In destructor 'Halide::Internal::ErrorReport::~ErrorReport()':
/home/jimmyoic/TensorComprehensions/third-party/halide/src/Error.cpp:121:15: error: exception handling disabled, use -fexceptions to enable
         throw err;
               ^
At global scope:
cc1plus: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
cc1plus: all warnings being treated as errors

Note that since I already had protobuf 2.6 on my server, I built protobuf 3.4 and changed the path of build.sh where it finds protobuf.

BTW, is it possible to build those third-party by myself rather than through the build script? I want to make sure how to correctly configure this (if this works).

Thanks!

**Comment by prigoyal** [comment]
Hi @jimmyoic , you all the third parties are build from source. The error you are getting requires building clang+llvm again by following these instructions https://facebookresearch.github.io/TensorComprehensions/installation_non_conda.html#step-3-install-clang-llvm
These instructions enable exceptions handling for llvm which was previously disabled. 

So, can you try doing a build for clang+llvm from  **scratch**  and retry building TC afterwards?

Thanks for reaching out.

**Comment by jimmyoic** [comment]
Hi,
I have built it from scratch and followed the link, it didn't work. 
Did I miss any configure? 
${CMAKE_VERSION} -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_OCAMLDOC=OFF -DLLVM_INSTALL_OCAMLDOC_HTML_DIR=/tmp -DLLVM_OCAML_INSTALL_PATH=/tmp -DCMAKE_INSTALL_PREFIX=${CLANG_PREFIX} -DLLVM_TARGETS_TO_BUILD=X86 -DCOMPILER_RT_BUILD_CILKTOOLS=OFF -DLLVM_ENABLE_CXX1Y=ON -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_BUILD_TESTS=OFF -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_LLVM_DYLIB=ON  -DLLVM_ENABLE_RTTI=ON ../llvm/

Thanks!

**Comment by ftynse** [comment]
Could you please a gist with build process output so that we see how exactly it did not work?

**Comment by jimmyoic** [comment]
Hi, thanks for the reply!
I follow the installation guide: check version of gcc/g++, install Clang+LLVM with the same command. Since I already have CUDA/Cudnn, so I skip that step. It all works perfectly until the installation of TC. I run the following command (exactly the same with the guide): 
BUILD_TYPE=Release PYTHON=$(which python3) WITH_CAFFE2=OFF CLANG_PREFIX=$HOME/clang+llvm-tapir5.0 ./build.sh --all

and when it begins to build Halide, it pops out the error:
![image](https://user-images.githubusercontent.com/7804036/36844376-734a5152-1d8d-11e8-8ae8-8c69f8786faa.png)

**Comment by ftynse** [comment]
It appears that the build is not picking up the right version of LLVM: there is `-fno-exceptions` in halide build commands, and it make come from querying cxxflags from a wrong `llvm-config`.

It is quite hard to debug from a partial output.  Please copy the full output of `build.sh` into a [gist](https://gist.github.com/) and post it here.

**Comment by prigoyal** [comment]
@jimmyoic can you run the following command and copy paste the output here

```
$HOME/clang+llvm-tapir5.0/bin/llvm-config --cxxflags
```

this will tell us if the llvm+clang build os okay.

**Comment by jimmyoic** [comment]
The output is the following:
![image](https://user-images.githubusercontent.com/7804036/36845088-5a7bac54-1d90-11e8-8d43-f44d00a5a932.png)

-I/home/cgilab/clang+llvm-tapir5.0/include  -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++1y -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -O3   -fno-exceptions -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS

**Comment by prigoyal** [comment]
@jimmyoic as you can see you have **-fno-exceptions** in your llvm build, that definitely means that the llvm build is incorrect. You can try the suggestion and remove the llvm build you have, and re-build it with the above command? make sure that cmake has ```-DLLVM_ENABLE_EH=ON``` in it.

Once you have done that, run 
```
$HOME/clang+llvm-tapir5.0/bin/llvm-config --cxxflags
```
again and send us the output.

**Comment by prigoyal** [comment]
great to know @jimmyoic , thanks for confirming. I'll close this issue now, it seems to be resolved. Please feel free to reach out to us if you have any questions :)
